###################
# aliases for Marco
###################
alias ifif="ifdown eth0 && ifup eth0"
alias e="exit"
alias projs="cd ~/projects/Onebip"
alias ou="cd ~/projects/Onebip/onebip-ultimate"
alias front="cd ~/projects/Onebip/onebip-panel/front"
alias rest="cd ~/projects/Onebip/onebip-panel/rest"
alias restlogs="cd /var/www/data/rest/logs"
alias book="cd ~/projects/Onebip/bookclub"
alias aliens="cd ~/projects/Onebip/bookclub/alienInvasion/faust-js"
alias legacy="cd ~/projects/Onebip/onebip"
alias le="cd ~/projects/Onebip/onebip"
alias gmm="git merge master"
alias grha="git reset --hard"
alias ost="cd ~/projects/Onebip/operation-support-tools"
alias lib="cd ~/projects/Onebip/onebip-libraries"
alias dem="cd ~/projects/Onebip/demetra"
alias conn="cd ~/projects/Onebip/connectivity"
alias con="cd ~/projects/Onebip/connectivity"
alias car="cd ~/projects/Onebip/caronte"
alias plu="cd ~/projects/Onebip/plutone"
alias pan="cd ~/projects/Onebip/panel"
alias 1dk="cd ~/projects/Onebip/1dk-android"
alias panel="cd ~/projects/Onebip/panel"
alias pan2="cd ~/projects/Onebip/onebip-panel"
alias panel2="cd ~/projects/Onebip/onebip-panel"
alias sub="cd ~/projects/Onebip/subscription-engine"
alias docs="cd ~/projects/Onebip/documentations"
alias pun="vendor/bin/phpunit "
alias puf="vendor/bin/phpunit --filter"
alias phplog="cd /var/log"
alias apachelogs="cd /var/log/apache2"
alias cleanup="/usr/local/bin/cleanup.sh"
alias cleanupsh="/usr/local/bin/cleanup.sh"
alias lessphplog="less /var/log/php.log"
alias tailphplog="tail -f /var/log/php.log"
alias tailuilog="tail -f /var/log/onebip/onebip/ultimate-ui*.log"
alias tailseleniumlog="tail -f /opt/selenium/selenium.log"
alias tailexclog="tail -f /var/log/onebip/onebip/ultimate-caught-exceptions*.log"
alias tailcaulog="tail -f /var/log/onebip/onebip/ultimate-caught-exceptions*.log"
alias viphplog="vim /var/log/php.log"
alias vimphplog="vim /var/log/php.log"
alias lllogs="ll /var/log/onebip/onebip"
alias applogs="cd /var/log/onebip/onebip"
alias nodeinspector="ui-spec/node_modules/.bin/node-inspector --web-port=8070 &"
alias ni="ui-spec/node_modules/.bin/node-inspector --web-port=8070 &"
alias figrep="find . | grep "
alias higrep="history | grep "
alias ag="ack-grep "
alias gprebase="git pull --rebase"
alias v1="vim /etc/apache2/sites-enabled/www.dev.onebip.com.conf"
alias v2="vim /etc/apache2/sites-enabled/www.dev.onebip.com-ssl.conf"
alias pd="phing dd"
alias pde="phing dd-end2end"
alias pfde="phing fast-dd-end2end"
alias pfd="phing fast-dd"
alias pl="phing -l"
alias pds="phing dds"
alias pfb="phing force-bk"
alias pfbk="phing force-bk"
alias pui="phing ui-spec-unit"
alias pcd="phing clean-dev"
alias mu="ui-spec/node_modules/mocha/bin/mocha ui-spec/unit"
alias mi="ui-spec/node_modules/mocha/bin/mocha ui-spec/integration"
alias mud="ui-spec/node_modules/mocha/bin/mocha --debug-brk ui-spec/unit"
alias me="ui-spec/node_modules/mocha/bin/mocha ui-spec/state_machine_exerciser"
alias mau="ui-spec/node_modules/mocha/bin/mocha spec"
alias ma="ui-spec/node_modules/mocha/bin/mocha ui-spec/acceptance -t 30000"
alias ms="ui-spec/node_modules/mocha/bin/mocha ui-spec/stack -t 5000"
alias sel='/bin/java -client -Xmx500m -Xss1024k -jar /opt/selenium/selenium-server-standalone-2.39.0.jar -log /opt/selenium/selenium.log'
alias uip='php /var/www/onebip/connectivity/scripts/userIsPoor.php '
alias exp='php /var/www/onebip-ultimate/scripts/SetExpenditure.php '
alias setexp='php /var/www/onebip-ultimate/scripts/SetExpenditure.php '
alias valiases="vim ~/.bash_aliases"
alias gralias="alias | grep $@"

# vim: ft=sh:sw=2:ts=2
function bash_aliases_find() { local terms="$@"; grep "^\s*alias.*${terms// /.*}" ~/.bash_aliases | sort | cut -d" " -f2; } 
function bash_aliases_edit() { vim ~/.bash_aliases; }
function bash_aliases_source() { source ~/.bash_aliases; }
function bash_aliases_edit_source() { bash_aliases_edit; bash_aliases_source; } 
function git_add() { git add "$@"; } 
function git_files_modified_edit() { vim $(git diff --name-only); } 
function git_branch() { git branch "$@"; } 
function git_branch_all { git branch --all "$@"; } 
function git_commit { git commit "$@"; } 
function git_commit_amend { git commit --amend "$@"; } 
function git_commit_message { git commit --message "$@"; } 
function git_checkout { git checkout "$@"; } 
function git_checkout_branch { git checkout -b "$@"; } 
function git_checkout_master { git checkout master; } 
function git_diff { git diff "$@"; } 
function git_diff_staged { git diff --staged "$@"; } 
function git_log { git log "$@"; } 
function git_log_new_here { git log master..HEAD; } 
function git_log_patch { git log --patch "$@"; } 
function git_log_stat { git log --stat "$@"; } 
function git_remote { git remote "$@"; } 
function git_remote_verbose { git remote --verbose "$@"; } 
function git_see { git log --graph --oneline --decorate --all --abbrev-commit "$@"; } 
function git_stash { git stash "$@"; } 
function git_status { git status "$@"; } 
function git_push_u_origin_head { git push -u origin HEAD; } 
function git_pullall { git pull "$@" && git submodule update --init --recursive; } 
function git_cherry_pick { git cherry-pick "$@"; } 
function git_submodule_update { git submodule update; } 
function tmux_config_edit { vim ~/.tmux.conf; } 
function vim_config_edit { vim ~/.vimrc; } 
##############################
alias a=bash_aliases_find
alias bae=bash_aliases_edit
alias baes=bash_aliases_edit_source
alias bas=bash_aliases_source
alias ga=git_add
alias gb=git_branch
alias gba=git_branch_all
alias gci=git_commit
alias gcia=git_commit_amend
alias gcim=git_commit_message
alias gco=git_checkout
alias gcob=git_checkout_branch
alias gcom=git_checkout_master
alias gcp=git_cherry_pick
alias gd=git_diff
alias gdoh="git diff origin HEAD"
alias gdnh=git_diff_new_here
alias gds=git_diff_staged
alias gl=git_log
alias glnh=git_log_new_here
alias glp=git_log_patch
alias gls=git_log_stat
alias gme=git_files_modified_edit
alias gpoh=git_push_u_origin_head
alias gpla=git_pullall
alias gr=git_remote
alias grv=git_remote_verbose
alias gs=git_status
alias gsee=git_see
alias gsh=git_stash
alias gsu=git_submodule_update
alias tce=tmux_config_edit
alias vce=vim_config_edit
